### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by one-more-minute** [JunoLab/atom-julia-client#10]
I'd like to get started planning out where our IDE work will go over the next few months. There are a few things I'd particularly like to see happen:

- [ ] Graphics and Plotting, including separate plotting pane
- [x] Error line highlighting and linking, as in LT
- [ ] Linting
- [ ] Console autocompletion
- [ ] Single-keystroke access to docs
- [ ] Integration between autocompletion and documentation (e.g. signatures and one-line summaries)
- [ ] Integrated plotting

What else is high on people's priority lists? All suggestions are welcome, and if someone is willing to work on a feature I'm very happy to add it to the roadmap.

**Comment by malmaud** [comment]
This isn't really *high* on my list, but: a pane that shows the current variables in the environment and a brief summary of their types and values. Bonus: double-click a variable to automatically plot it in a way sensible for its type.

**Comment by malmaud** [comment]
Also, hotkeys to efficiently switch between panes, especially the editor and console.

**Comment by datnamer** [comment]
What about a spreadsheet like dataframe and array explorer? Spyder and Rstudio both have this feature.

**Comment by Varanas** [comment]
Only a couple of lines, since I'm nowhere near an actual PC right now :

Regarding plotting: I'm not sure whether a plotting pane really is the way to go. Imo displaying the plot in its own floating window (Matlab style) is more convenient, and should be easily done via atom-shell (or whatever it's called now)... 

The last point is something that Visual Studio does nicely,  so that's how I'd try to do it here too. 

And I'd like to second @malmaud 's suggestion of a variable browser.

**Comment by malmaud** [comment]
Well, 'Matlab style' for plotting was actually my inspiration, since it lets you dock the floating plot window onto the main workspace, which I was my usual workflow. But whether it's docked or floated in the Atom IDE isn't a big deal to me compared to other wish-list features.

**Comment by Varanas** [comment]
Heh, good point. I never used Matlab with docked plots since I always found it super convenient to be able to compare multiple plots by having them in their own window and next to each other (poor man's subplot, so to speak ;-)). 
But yeah, that's just a matter of taste... 
Thinking on it: Juno can only handle plots for some plotting packages realistically, right? No one would really want to lose the interactivity of a pyplot-plot,  and drawing that in Atom seems rather impossible to me.

**Comment by malmaud** [comment]
It could draw as an SVG and then just be rendered natively by chromium,
couldnt it?

**Comment by Varanas** [comment]
Yeah,  sure, but that'd mean no more interactivity. What might be nice is a small rendered plot inline or underline which opens the real plot somewhere when clicked on.

**Comment by one-more-minute** [comment]
Integrated plotting is definitely important – I added that to the readme. I'm planning to support both inline panes and windows equally well so that shouldn't be an issue.

I'm a big fan of the idea of having a really nice spreadsheet component for dataframes, matrices etc., but getting that working really well is a fairly large project.

**Comment by datnamer** [comment]
@one-more-minute  Jupyter team is working on an IDEish thing called phosphor. This is the spreadsheet component: https://github.com/jupyter/spreadsheet 

Perhaps it would be good to piggy pack off their progress.

**Comment by one-more-minute** [comment]
Ok, that looks interesting. It would be great if someone could look into the feasibility of integrating that work with Atom.

**Comment by ViralBShah** [comment]
+1 to spreadsheet view. I can imagine tons of interesting things one can do with this. Perhaps this can be implemented in Escher. Cc: @shashi

**Comment by sbromberger** [comment]
A question: how will this be different from Hydrogen (https://atom.io/packages/hydrogen) which is a good package in its own right? I'm excited to see all these efforts to get a nice IDE for Julia on Atom - don't get me wrong - but I'm confused by the number of choices.

**Comment by mmoh** [comment]
Out of curiosity what is the goal behind this project? Is the intent to provide some IDE like features that can mimic the matlab interface?  Or  more generally to provide a real IDE for Julia along the lines of MATLAB (which would be great); If so,  don't you think that atom would be too  limiting in the  long run when needing to add advanced functionality? I mean atom has some real potential, but I can't help notice  how slow it is and the number of times it has frozen has made it unusable for me.

**Comment by malmaud** [comment]
It is intended to be like Matlab/RStudio. In the general case, an Atom panel is just a web browser that can handle arbitrary html and javascript, so I'm not sure I see why it wouldn't have enough  power.

**Comment by sbromberger** [comment]
I'm not sure I get this objection either - I know the plural of "anecdote" is not "data" but I've been using Atom now for about 6 months (since pre-1.0) and the speed hasn't been an issue.

(The inability to open large files - now fixed, I believe - was an issue, however.)

I'm still wondering what this package will offer over Hydrogen. It might make sense to combine efforts to produce something that's truly outstanding.

**Comment by one-more-minute** [comment]
@sbromberger Hydrogen is nice, but very much tied to IPython. My set of packages is intended to be really modular, with ink providing the UI components (inline results, console etc.) and julia-client hooking that UI up to a Julia backend. You could hook those UI bits up to an IJulia kernel too, if you wanted (to recreate something like Hydrogen), but you'd find it pretty limiting: The notebook interface is fundamentally very different from an editor+console, and mashing the two together doesn't really work that well.

@mmoh Atom's performance is definitely still a bit variable on different systems. For me it works great, though I've heard it can freeze up a bit more for others. The team at GitHub really care a lot about performance, though, and that's improving quickly. We've reviewed a lot of options and I really think it's the only viable route forward, at least in the short term.

**Comment by Varanas** [comment]
I kinda hope that it'd be *more* than just matlab -- the instREPL and the stuff Mike does with evaling into modules is a very useful (and powerful) utility imo. And let's be honest: Not everything the Matlab IDE does is all that great.
Your concerns about Atom are kinda understandable regarding stability and speed (compared to, say, SublimeText or something like that), but then it's very powerful and extendable from what I've seen so far and is furthermore backed by GitHub. I wouldn't worry about it in the long term.

About Hydrogen: It only works with iPython/Jupyter -- that's reason enough for me to look for something else. I find it a bit annoying to have to set up python in order to get a nice Julia IDE. Though Hydrogen looks really nice, granted ;)

**Comment by sbromberger** [comment]
@Varanas ah, that's definitely something I overlooked, since I use both Python and Julia. Thanks for bringing that restriction up.

**Comment by Ken-B** [comment]
I don't know if this is the right place to ask, but what I really enjoy from an editor (Matlab, eclipse, visual studio, Rstudio, even Excel VBA) is the ability to set breakpoints and step through/debug the code. Would that be possible with atom?

Let me know if I can do anything to help achieve such a visual debugger. 

I'm also excited by atom and even more you guys working on it. Thanks and good luck!

**Comment by mmoh** [comment]
That is good to hear. I'm looking forward to the future of this project. I hope one day I don't have to use MATLAB. The IDE, fast 2d/3d plotting and documentation are really the only things keeping me. I have been testing Julia and playing around with it bit by bit and am really enjoying it thus far.

@sbromberger  True it is my anecdote. But yesterday I was installing this package and several other themes and it atom consistently froze after each installation (even after a syntax download)  to the point where I had to shutdown and restart atom to get it working again. Again this is my experience on Windows. I've tested atom on my surface pro 3 and again same issues so I don't think its my computer in particular. I'm not sure if the developers tested atom on windows but it really sucks as of version 1.09.

**Comment by malmaud** [comment]
We all want that, but there is no debugger for Julia (text or GUI) at the
moment because of how hard a technical challenge it is to write one for a
JITed language like Julia. The core debugging support will eventually be
developed for Julia, at which time it should be relatively straightforward
to add a GUI.

**Comment by Varanas** [comment]
@mmoh Just to provide another data point/anecdote: I too have been using Atom for a bit on Windows and so far haven't had any crashes or freezes (at least none that weren't entirely my fault), although Atom *feels* a bit slow to me sometimes. But then again the Matlab IDE is pretty slowish too...

@Ken-B Debugging is in the works, iirc, but a long way from done. Stepping through code on the other hand is dead simple with Juno (with one major drawback: Can't step into a function call): You just eval one line after the other or select a block and eval that.

**Comment by davidanthoff** [comment]
Are there plans to simplify the setup process? It would be great if there was just one julia package that one can install from within Atom, and then everything just works.

**Comment by nilshg** [comment]
@davidanthoff As Mike explained [here](http://discuss.junolab.org/t/announcing-julia-ide-work-in-atom/297/4?u=nilshg), the goal would probably be to phase out Juno/LightTable, and make Juno/Atom the standard bundle. Given that JunoLT is currently available as an "official" IDE bundle on the julialang website, I suppose that in the (near?) future, a Juno/Atom bundle could take its place, with a similar out-of-the-box experience.

Of course this would require 0.4 to be released first, as Atom requires 0.4 and you wouldn't want an "official" IDE based on a nightly build...

**Comment by davidanthoff** [comment]
I almost think that the most user friendly would be to actually not have a bundled download for Atom/Julia, but instead just ask users to download Atom and then install ideally one package to get julia integration.

The JunoLT download always had the problem that it was just a zip and didn't have an installer. For inexperienced users that is a real hurdle. But getting a proper setup program going that handles all the required corner cases is *really* difficult. I'm think especially about handling Atom updates, julia updates etc. in some meaningful way.

I could see an argument that the atom plugin could download and install julia itself, although I almost feel it would make more sense to try to get the official julia setups somehow register installed versions of julia (on Windows e.g. in the registry) so that things like the Atom plugin have an easier time finding the julia.exe.

**Comment by Varanas** [comment]
I agree, @davidanthoff, though I can see the appeal of a complete bundle.

But since Atom is so much more than just a soon-to-be base for a Julia IDE, an extra step in the installation is warranted, imho. Some kind of three step installation would be my choice, I think: Download and install Atom, download and install Julia, install `julia-client` from Atom which handles all dependecies (on the Atom *and* the Julia side, which shouldn't be all that difficult).

Regarding registering Julia in the registry: Isn't there an option to add Julia to the `PATH` when installing? We could encourage that and not worry about anything else, right?

**Comment by one-more-minute** [comment]
It would definitely be cool to have the plugin auto download and update Julia. I don't see that happening for a while, though, unless someone is interested in stepping in to make it happen.

**Comment by sbromberger** [comment]
-1 for autodownloads (or at least -0 if we could disable it). I use several versions for testing and want to make sure my IDE doesn't overwrite my working environment

**Comment by Varanas** [comment]
Notifying when a new stable version of Julia is available and autoupdating `Atom.jl` would be a nice thing, imo.

**Comment by sbromberger** [comment]
@Varanas no issues with notification at all. Autoupdating isn't an Atom feature - notification is - so perhaps we could just do that? Autoupdate has security implications as well.

**Comment by nilshg** [comment]
Yes, I'm with Seth here, this might be a good idea when there's a stable Julia environment (1.0?), but currently with 0.3.11, a just released 0.4, and a 0.5.0-dev branch this doesn't make sense.

**Comment by one-more-minute** [comment]
Ok, when I say "auto-updating" I mean something like a popup that asks if you want to upgrade, and if you do saves the bother of downloading and linking everything. We certainly wouldn't want to overwrite environments by default. I very much doubt will have this before 1.0 anyway so it's not a huge deal.

**Comment by sbromberger** [comment]
@one-more-minute ah, that's more appealing. Is there any way to hook into Atom's squirrel notification when updates are available? That'd be really slick.

**Comment by davidanthoff** [comment]
I think the main short term thing would be to 

1) Make things such that users only have to install one Atom package (which might trigger the installation of other Atom packages, but it would be good if the user was shielded from that)
2) Have the plugin install and udpate the Atom.jl package
3) Get the ``JuliaParser`` folks to tag a version, so that no checkout is needed

I feel at that point the whole setup thing would be good enough for quite a while.

**Comment by ViralBShah** [comment]
I would like an auto-download prompt.
